#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${REPO_ROOT}"
source scripts/stream_exp/00_env.sh

banner "FINAL REPRODUCTION PREFLIGHT"

# Files needed before ANY training. Outputs generated by later steps are not
# checked here.
REQUIRED=(
    "${ORIGINAL_CFG}"
    "${ORIGINAL_CKPT}"
    "${FULL_CFG}"

    scripts/stream_exp/01_test_original.sh
    scripts/stream_exp/02_train_mh.sh
    scripts/stream_exp/03_test_mh.sh

    scripts/stream_exp/18_train_elastic_v4_bn_final.sh
    scripts/stream_exp/23_calibrate_causal_prefix_bn_bank.sh
    scripts/stream_exp/27_validate_causal_prefix_bn_bank.sh
    scripts/stream_exp/28_test_all_84_profiles_sap.sh
    scripts/stream_exp/29_profile_all_84_forward.sh
    scripts/stream_exp/38_calibrate_smooth_contention.sh
    scripts/stream_exp/40_profile_all_84_smooth_contention.sh
    scripts/stream_exp/41_audit_tv_stream3d_controller.sh
    scripts/stream_exp/42_smoke_tv_stream3d_online.sh
    scripts/stream_exp/44_run_tv_stream3d_30hz_levels.sh
    scripts/stream_exp/45_run_tv_stream3d_30hz_random50.sh

    scripts/stream_exp/46_run_original_streamdsgn_30hz_random50.sh
    scripts/stream_exp/48_run_original_streamdsgn_no_load.sh

    scripts/stream_exp/51_train_mtd_heads.sh
    scripts/stream_exp/51_run_mtd_three_head_no_load.sh
    scripts/stream_exp/52_run_mtd_three_head_random50.sh

    scripts/stream_exp/55_run_transtreaming_v2_best_no_load.sh
    scripts/stream_exp/56_run_transtreaming_v2_best_random50.sh

    tools/build_contention_latency_table_smooth.py

    tools/build_mtd_train_configs.py
    tools/smoke_mtd_head_training.py
    tools/mtd_three_head_runtime.py

    pcdet/datasets/kitti_streaming/stereo_kitti_streaming.py
    pcdet/models/__init__.py
    pcdet/models/detectors_stream/__init__.py

    tools/eval_transtreaming_v2_stream.py
    pcdet/models/fusion_module/transtreaming_bev_tat.py
    pcdet/models/detectors_stream/transtreaming_stream_v2.py
    configs/stream/kitti_models/stream_dsgn_r18-token_prev3_prev2_prev_next-mh_residual-transtreaming_tat_v2_15ep.yaml
)

missing=0
for f in "${REQUIRED[@]}"; do
    if [ ! -f "${f}" ]; then
        echo "[MISSING] ${f}"
        missing=1
    fi
done

if [ "${missing}" -ne 0 ]; then
    echo
    echo "[ERROR] Reproduction tree is incomplete."
    echo "Commit/copy every missing FINAL file before publishing the repository."
    exit 2
fi

if [ "${ORIGINAL_CFG}" = "${FULL_CFG}" ] || \
   [ "${ORIGINAL_CKPT}" = "${FULL_CKPT}" ]; then
    echo "[ERROR] ORIGINAL_* must not equal FULL_*."
    exit 3
fi

for sh in \
    scripts/stream_exp/01_test_original.sh \
    scripts/stream_exp/02_train_mh.sh \
    scripts/stream_exp/03_test_mh.sh \
    scripts/stream_exp/18_train_elastic_v4_bn_final.sh \
    scripts/stream_exp/23_calibrate_causal_prefix_bn_bank.sh \
    scripts/stream_exp/27_validate_causal_prefix_bn_bank.sh \
    scripts/stream_exp/28_test_all_84_profiles_sap.sh \
    scripts/stream_exp/29_profile_all_84_forward.sh \
    scripts/stream_exp/38_calibrate_smooth_contention.sh \
    scripts/stream_exp/40_profile_all_84_smooth_contention.sh \
    scripts/stream_exp/41_audit_tv_stream3d_controller.sh \
    scripts/stream_exp/42_smoke_tv_stream3d_online.sh \
    scripts/stream_exp/44_run_tv_stream3d_30hz_levels.sh \
    scripts/stream_exp/45_run_tv_stream3d_30hz_random50.sh \
    scripts/stream_exp/46_run_original_streamdsgn_30hz_random50.sh \
    scripts/stream_exp/48_run_original_streamdsgn_no_load.sh \
    scripts/stream_exp/51_train_mtd_heads.sh \
    scripts/stream_exp/51_run_mtd_three_head_no_load.sh \
    scripts/stream_exp/52_run_mtd_three_head_random50.sh \
    scripts/stream_exp/55_run_transtreaming_v2_best_no_load.sh \
    scripts/stream_exp/56_run_transtreaming_v2_best_random50.sh
do
    bash -n "${sh}"
done

python -m py_compile \
    tools/build_contention_latency_table_smooth.py \
    tools/mtd_three_head_runtime.py \
    tools/eval_transtreaming_v2_stream.py \
    pcdet/models/fusion_module/transtreaming_bev_tat.py \
    pcdet/models/detectors_stream/transtreaming_stream_v2.py

# Semantic checks for patches/registration that a simple file-exists test misses.
grep -q "_maybe_add_mtd_future_tags" \
    pcdet/datasets/kitti_streaming/stereo_kitti_streaming.py || {
    echo "[ERROR] dataset MTD future-tag patch is missing"
    exit 10
}

grep -q "_maybe_add_transtreaming_past_tags" \
    pcdet/datasets/kitti_streaming/stereo_kitti_streaming.py || {
    echo "[ERROR] dataset Transtreaming past-tag patch is missing"
    exit 11
}

grep -q "transtreaming_stream_v2" \
    pcdet/models/detectors_stream/__init__.py || {
    echo "[ERROR] transtreaming_stream_v2 detector registration is missing"
    exit 12
}

python - <<'PY'
import yaml
from pathlib import Path

p = Path(
    "configs/stream/kitti_models/"
    "stream_dsgn_r18-token_prev3_prev2_prev_next-"
    "mh_residual-transtreaming_tat_v2_15ep.yaml"
)
cfg = yaml.safe_load(p.read_text())

assert cfg["MODEL"]["NAME"] == "transtreaming_stream_v2", cfg["MODEL"]["NAME"]

ts = cfg["MODEL"]["TRANSTREAMING"]
assert list(ts["TRAIN_FUTURE_STEPS"]) == [1, 2, 4, 8], ts["TRAIN_FUTURE_STEPS"]
assert list(ts["EVAL_FUTURE_STEPS"]) == [1], ts["EVAL_FUTURE_STEPS"]
assert int(cfg["OPTIMIZATION"]["NUM_EPOCHS"]) == 15, cfg["OPTIMIZATION"]["NUM_EPOCHS"]

print("[PASS] Transtreaming config semantics")
PY

echo
echo "[PASS] source tree / shell syntax / Python syntax / semantic preflight"
