#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path

CLASSES = ("Car", "Pedestrian", "Cyclist")
IOUS = ("0.5", "0.7")
METRICS = ("bev", "3d")
DIFFS = ("easy", "moderate", "hard")


def parse_paper_metrics(path: Path):
    values = {}
    cur_cls = None
    cur_iou = None

    class_re = re.compile(r"^(Car|Pedestrian|Cyclist)\s*$")
    iou_re = re.compile(r"^\s*IoU=(0\.[57])\s*$")
    metric_re = re.compile(
        r"^\s*sAP(BEV|3D)\s*:\s*"
        r"([-+0-9.eE]+)\s*,\s*([-+0-9.eE]+)\s*,\s*([-+0-9.eE]+)\s*$"
    )

    for raw in path.read_text(errors="replace").splitlines():
        m = class_re.match(raw)
        if m:
            cur_cls = m.group(1)
            cur_iou = None
            continue

        m = iou_re.match(raw)
        if m:
            cur_iou = m.group(1)
            continue

        m = metric_re.match(raw)
        if m and cur_cls and cur_iou:
            metric = "bev" if m.group(1) == "BEV" else "3d"
            vals = [float(m.group(i)) for i in (2, 3, 4)]
            for diff, val in zip(DIFFS, vals):
                key = f"{cur_cls.lower()}_{metric}_iou{cur_iou.replace('.', '')}_{diff}"
                values[key] = val

    expected = 3 * 2 * 2 * 3
    if len(values) != expected:
        raise RuntimeError(
            f"{path}: expected {expected} paper metrics, parsed {len(values)}"
        )
    return values


def locate_one(root: Path, filename: str):
    hits = list(root.rglob(filename))
    if not hits:
        return None
    if len(hits) > 1:
        # Prefer the deepest result generated by test_elastic_stream_v4_bn.py.
        hits.sort(key=lambda p: len(p.parts), reverse=True)
    return hits[0]


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--schedule_tsv", required=True)
    p.add_argument("--result_root", required=True)
    p.add_argument("--output_csv", required=True)
    p.add_argument("--output_json", default=None)
    args = p.parse_args()

    result_root = Path(args.result_root)
    with open(args.schedule_tsv, newline="") as f:
        profiles = list(csv.DictReader(f, delimiter="\t"))

    rows = []
    missing = []

    metric_columns = []
    for cls in CLASSES:
        for metric in METRICS:
            for iou in IOUS:
                for diff in DIFFS:
                    metric_columns.append(
                        f"{cls.lower()}_{metric}_iou{iou.replace('.', '')}_{diff}"
                    )

    for pinfo in profiles:
        pid = int(pinfo["id"])
        tag = pinfo["tag"]
        profile_root = result_root / f"{pid:03d}_{tag}"
        paper_path = locate_one(profile_root, "paper_sap.txt")

        row = dict(pinfo)
        row["status"] = "OK" if paper_path else "MISSING"
        row["paper_sap_path"] = str(paper_path) if paper_path else ""

        if paper_path is None:
            missing.append(pid)
            for c in metric_columns:
                row[c] = ""
            for c in (
                "mean_service_ms", "p50_service_ms", "p90_service_ms",
                "p99_service_ms", "drop_rate", "deadline_miss_rate",
                "reference_mean3d_moderate"
            ):
                row[c] = ""
            rows.append(row)
            continue

        metrics = parse_paper_metrics(paper_path)
        row.update(metrics)

        # Convenience score only.  Do NOT treat this as the final controller
        # objective unless the paper later explicitly adopts this definition.
        row["reference_mean3d_moderate"] = (
            metrics["car_3d_iou07_moderate"]
            + metrics["pedestrian_3d_iou05_moderate"]
            + metrics["cyclist_3d_iou05_moderate"]
        ) / 3.0

        summary_path = locate_one(profile_root, "summary.json")
        summary = {}
        if summary_path:
            summary = json.loads(summary_path.read_text())
        for key in (
            "mean_service_ms", "p50_service_ms", "p90_service_ms",
            "p99_service_ms", "drop_rate", "deadline_miss_rate"
        ):
            row[key] = summary.get(key, "")

        rows.append(row)

    fixed_columns = [
        "id", "schedule", "tag",
        "res2", "res3", "res4", "fpn", "stereo", "rpn",
        "status",
        "reference_mean3d_moderate",
        "mean_service_ms", "p50_service_ms", "p90_service_ms",
        "p99_service_ms", "drop_rate", "deadline_miss_rate",
    ]
    columns = fixed_columns + metric_columns + ["paper_sap_path"]

    out_csv = Path(args.output_csv)
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    with out_csv.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=columns)
        w.writeheader()
        w.writerows(rows)

    ok_rows = [r for r in rows if r["status"] == "OK"]
    ranking = sorted(
        ok_rows,
        key=lambda r: float(r["reference_mean3d_moderate"]),
        reverse=True,
    )

    result = {
        "expected_profiles": 84,
        "completed_profiles": len(ok_rows),
        "missing_profile_ids": missing,
        "csv": str(out_csv),
        "top10_reference_mean3d_moderate": [
            {
                "id": int(r["id"]),
                "schedule": r["schedule"],
                "score": float(r["reference_mean3d_moderate"]),
            }
            for r in ranking[:10]
        ],
    }

    if args.output_json:
        out_json = Path(args.output_json)
        out_json.parent.mkdir(parents=True, exist_ok=True)
        out_json.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n")

    print(json.dumps(result, indent=2, ensure_ascii=False))
    if missing:
        print(
            "[INCOMPLETE] Re-run the batch script; completed profiles are skipped automatically."
        )
    else:
        print("[DONE] All 84 profiles have paper_sap.txt results.")


if __name__ == "__main__":
    main()

